-- MySQL Script generated by MySQL Workbench
-- Mon Jan 27 10:48:34 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema winter_claw
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `winter_claw` ;

-- -----------------------------------------------------
-- Schema winter_claw
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `winter_claw` DEFAULT CHARACTER SET utf8 ;
USE `winter_claw` ;

-- -----------------------------------------------------
-- Table `winter_claw`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `winter_claw`.`products` ;

CREATE TABLE IF NOT EXISTS `winter_claw`.`products` (
  `idproducts` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  `summary` TINYTEXT NOT NULL,
  `description` TEXT NOT NULL,
  `price` DECIMAL(8,2) NOT NULL,
  `height` DECIMAL(5,2) NULL,
  `lenght` DECIMAL(5,2) NULL,
  `width` DECIMAL(5,2) NULL,
  `weight` DECIMAL(5,2) NULL,
  `maxstock` INT NOT NULL,
  `currentstock` INT NOT NULL,
  PRIMARY KEY (`idproducts`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `winter_claw`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `winter_claw`.`categories` ;

CREATE TABLE IF NOT EXISTS `winter_claw`.`categories` (
  `idcategories` INT NOT NULL AUTO_INCREMENT,
  `category` VARCHAR(45) NOT NULL,
  `idparentcategories` INT NULL,
  PRIMARY KEY (`idcategories`),
  INDEX `fk_categories_categories1_idx` (`idparentcategories` ASC),
  UNIQUE INDEX `category_UNIQUE` (`category` ASC),
  CONSTRAINT `fk_categories_categories1`
    FOREIGN KEY (`idparentcategories`)
    REFERENCES `winter_claw`.`categories` (`idcategories`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `winter_claw`.`countries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `winter_claw`.`countries` ;

CREATE TABLE IF NOT EXISTS `winter_claw`.`countries` (
  `idcountries` INT NOT NULL AUTO_INCREMENT,
  `country` VARCHAR(55) NOT NULL,
  `ISO3` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`idcountries`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `winter_claw`.`cities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `winter_claw`.`cities` ;

CREATE TABLE IF NOT EXISTS `winter_claw`.`cities` (
  `idcities` INT NOT NULL AUTO_INCREMENT,
  `city` VARCHAR(60) NOT NULL,
  `countries_idcountries` INT NOT NULL,
  PRIMARY KEY (`idcities`),
  INDEX `fk_cities_countries1_idx` (`countries_idcountries` ASC),
  CONSTRAINT `fk_cities_countries1`
    FOREIGN KEY (`countries_idcountries`)
    REFERENCES `winter_claw`.`countries` (`idcountries`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '		';


-- -----------------------------------------------------
-- Table `winter_claw`.`postal_codes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `winter_claw`.`postal_codes` ;

CREATE TABLE IF NOT EXISTS `winter_claw`.`postal_codes` (
  `idpostal_codes` INT NOT NULL AUTO_INCREMENT,
  `postal_code` VARCHAR(13) NOT NULL,
  `cities_idcities` INT NOT NULL,
  PRIMARY KEY (`idpostal_codes`),
  INDEX `fk_postal_codes_cities1_idx` (`cities_idcities` ASC),
  CONSTRAINT `fk_postal_codes_cities1`
    FOREIGN KEY (`cities_idcities`)
    REFERENCES `winter_claw`.`cities` (`idcities`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `winter_claw`.`addresses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `winter_claw`.`addresses` ;

CREATE TABLE IF NOT EXISTS `winter_claw`.`addresses` (
  `idaddresses` INT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(100) NOT NULL,
  `house_number` VARCHAR(5) NOT NULL,
  `postal_codes_idpostal_codes` INT NOT NULL,
  PRIMARY KEY (`idaddresses`),
  INDEX `fk_addresses_postal_codes1_idx` (`postal_codes_idpostal_codes` ASC),
  CONSTRAINT `fk_addresses_postal_codes1`
    FOREIGN KEY (`postal_codes_idpostal_codes`)
    REFERENCES `winter_claw`.`postal_codes` (`idpostal_codes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `winter_claw`.`account_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `winter_claw`.`account_status` ;

CREATE TABLE IF NOT EXISTS `winter_claw`.`account_status` (
  `idaccount_status` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idaccount_status`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `winter_claw`.`accounts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `winter_claw`.`accounts` ;

CREATE TABLE IF NOT EXISTS `winter_claw`.`accounts` (
  `idaccounts` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(60) NOT NULL,
  `password` TEXT NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `account_status_idaccount_status` INT NOT NULL,
  PRIMARY KEY (`idaccounts`),
  INDEX `fk_accounts_account_status1_idx` (`account_status_idaccount_status` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  CONSTRAINT `fk_accounts_account_status1`
    FOREIGN KEY (`account_status_idaccount_status`)
    REFERENCES `winter_claw`.`account_status` (`idaccount_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `winter_claw`.`persons`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `winter_claw`.`persons` ;

CREATE TABLE IF NOT EXISTS `winter_claw`.`persons` (
  `idperson` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `surname` VARCHAR(50) NOT NULL,
  `phone_number` VARCHAR(15) NULL,
  `addresses_idaddresses` INT NOT NULL,
  `accounts_idaccounts` INT NOT NULL,
  PRIMARY KEY (`idperson`),
  INDEX `fk_persons_addresses1_idx` (`addresses_idaddresses` ASC),
  INDEX `fk_persons_accounts1_idx` (`accounts_idaccounts` ASC),
  CONSTRAINT `fk_persons_addresses1`
    FOREIGN KEY (`addresses_idaddresses`)
    REFERENCES `winter_claw`.`addresses` (`idaddresses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_persons_accounts1`
    FOREIGN KEY (`accounts_idaccounts`)
    REFERENCES `winter_claw`.`accounts` (`idaccounts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `winter_claw`.`comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `winter_claw`.`comments` ;

CREATE TABLE IF NOT EXISTS `winter_claw`.`comments` (
  `idcomments` INT NOT NULL AUTO_INCREMENT,
  `comment` TINYTEXT NOT NULL,
  `accounts_idaccounts` INT NOT NULL,
  `products_idproducts` INT NOT NULL,
  PRIMARY KEY (`idcomments`),
  INDEX `fk_comments_accounts1_idx` (`accounts_idaccounts` ASC),
  INDEX `fk_comments_products1_idx` (`products_idproducts` ASC),
  CONSTRAINT `fk_comments_accounts1`
    FOREIGN KEY (`accounts_idaccounts`)
    REFERENCES `winter_claw`.`accounts` (`idaccounts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_products1`
    FOREIGN KEY (`products_idproducts`)
    REFERENCES `winter_claw`.`products` (`idproducts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `winter_claw`.`orders_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `winter_claw`.`orders_status` ;

CREATE TABLE IF NOT EXISTS `winter_claw`.`orders_status` (
  `idorders_status` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idorders_status`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `winter_claw`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `winter_claw`.`orders` ;

CREATE TABLE IF NOT EXISTS `winter_claw`.`orders` (
  `idorders` INT NOT NULL AUTO_INCREMENT,
  `order_date` DATE NOT NULL,
  `order_price` DECIMAL(8,2) NOT NULL,
  `orders_status_idorders_status` INT NOT NULL,
  `accounts_idaccounts` INT NOT NULL,
  PRIMARY KEY (`idorders`),
  INDEX `fk_orders_orders_status1_idx` (`orders_status_idorders_status` ASC),
  INDEX `fk_orders_accounts1_idx` (`accounts_idaccounts` ASC),
  CONSTRAINT `fk_orders_orders_status1`
    FOREIGN KEY (`orders_status_idorders_status`)
    REFERENCES `winter_claw`.`orders_status` (`idorders_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_accounts1`
    FOREIGN KEY (`accounts_idaccounts`)
    REFERENCES `winter_claw`.`accounts` (`idaccounts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `winter_claw`.`order_has_products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `winter_claw`.`order_has_products` ;

CREATE TABLE IF NOT EXISTS `winter_claw`.`order_has_products` (
  `idorder_has_products` INT NOT NULL AUTO_INCREMENT,
  `quantity` INT NOT NULL,
  `orders_idorders` INT NOT NULL,
  `products_idproducts` INT NOT NULL,
  PRIMARY KEY (`idorder_has_products`),
  INDEX `fk_order_has_products_orders1_idx` (`orders_idorders` ASC),
  INDEX `fk_order_has_products_products1_idx` (`products_idproducts` ASC),
  CONSTRAINT `fk_order_has_products_orders1`
    FOREIGN KEY (`orders_idorders`)
    REFERENCES `winter_claw`.`orders` (`idorders`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_has_products_products1`
    FOREIGN KEY (`products_idproducts`)
    REFERENCES `winter_claw`.`products` (`idproducts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `winter_claw`.`products_has_categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `winter_claw`.`products_has_categories` ;

CREATE TABLE IF NOT EXISTS `winter_claw`.`products_has_categories` (
  `idproducts_has_categories` INT NOT NULL AUTO_INCREMENT,
  `categories_idcategories` INT NOT NULL,
  `products_idproducts` INT NOT NULL,
  PRIMARY KEY (`idproducts_has_categories`),
  INDEX `fk_products_categories_categories1_idx` (`categories_idcategories` ASC),
  INDEX `fk_products_categories_products1_idx` (`products_idproducts` ASC),
  CONSTRAINT `fk_products_categories_categories1`
    FOREIGN KEY (`categories_idcategories`)
    REFERENCES `winter_claw`.`categories` (`idcategories`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_categories_products1`
    FOREIGN KEY (`products_idproducts`)
    REFERENCES `winter_claw`.`products` (`idproducts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
